id = "spice"
name = "SPICE"
version = "0.1.1"
schema_version = 1
authors = ["bytesiz3d"]
description = "SPICE/HSPICE/NGSPICE/PSPICE and Spectre netlist syntax highlighting"
repository = "https://github.com/bytesiz3d/zed-spice"

[grammars.spice]
repository = "https://github.com/bytesiz3d/tree-sitter-spice"
rev = "29aec755172aa0b5fa5cac2b96b0b728b8441938"
