id = "spice"
name = "SPICE"
version = "0.1.0"
schema_version = 1
authors = ["bytesiz3d"]
description = "SPICE/HSPICE/NGSPICE/PSPICE and Spectre netlist syntax highlighting"
repository = "https://github.com/bytesiz3d/zed-spice"

[grammars.spice]
repository = "https://github.com/bytesiz3d/tree-sitter-spice"
rev = "9f82b0afd9ae75d0a409c866c360f7f2d2a8cdad"
